config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "pages/profile", to: "pages#profile", as: "profile"
  resources :lists do
    member do
      get 'new_list_email'
    end
    resources :items, only: [ :index, :show, :new, :create, :edit, :update ] do
      member do
        patch 'toggle_complete'
        patch :move
      end
    end
  end
  resources :items, only: :destroy

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lists, only: [ :index, :show, :create, :destroy ] do
        resources :items, only: [ :index, :show, :update, :create, :destroy ]
      end
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User
  before_action :set_list, only: [ :show, :destroy ]
  def index
    @lists = policy_scope(List).order(created_at: :desc)
  end

  def show
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    authorize @list
    if @list.save
      render :show, status: :created
    else
      render_error
    end
  end

  def destroy
    @list.destroy
    head :no_content
  end

  private

  def set_list
    @list = List.find(params[:id])
    authorize @list
  end

  def list_params
    params.require(:list).permit(:name, :complete)
  end

  def render_error
    render json: { errors: @list.errors.full_messages },
      status: :unprocessable_entity
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :new_list_email]
  def index
    @lists = policy_scope(List).order(created_at: :desc)
  end

  def shows
  end

  def new
    @list = List.new
    authorize @list
  end

  def create
    @list = List.new(list_params)
    authorize @list
    @list.user = current_user
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  def new_list_email
    @user = current_user
    @email = params[:email]

    UserMailer.list_send(@list, @user, @email).deliver_now
    flash[:notice] = "List has been sent."
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :complete)
  end

  def set_list
    @list = List.find(params[:id])
    authorize @list
  end
end

app/views/lists/edit.html.erb
<h1>edit list</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<div class="container-sm">
  <% if policy(List).create? %>
    <%= link_to "Create list", new_list_path, class: "create-btn" %>
  <% end %>
  <% @lists.each do |list| %>
    <div class="d-flex justify-content-between align-items-center list-container">
      <div class="d-flex align-items-center">
        <label class="circle-box">
          <input type="checkbox" class="checkbox checkbox-round" />
          <span class="checkmark"></span>
        </label>
        <%= link_to "#{list.name.titleize}", list_path(list), class: "list-name" %>
      </div>
      <div>
        <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, list_path(list), class: "hidden list-icon", method: :delete, data: { confirm: "Are you sure?"} %>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container-sm">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: false, placeholder: "Enter list name" %>
    <%= f.submit "Create", class: "create-btn" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container-sm">
 <div class="list-header d-flex">
   <%= link_to "<i class='fas fa-chevron-left'></i>".html_safe, lists_path, class: "back-arrow" %>
   <h2><%= @list.name.titleize %></h2>
 </div>
 <%= link_to "Add Item", new_list_item_path(@list), class: "create-btn" %>
 <div id="list" data-controller="drag" data-drag-url="/lists/<%= @list.id %>/items/:id/move">
   <% @list.items.order(position: :asc).each do |item| %>
     <div data-id="<%= item.id %>" class="list-item d-flex justify-content-between">
       <div class="items">
         <h4 id="name-<%= item.id %>"><%= item.name.titleize %></h4>
         <% unless item.note.empty? %>
           <p>Notes: <%= item.note %></p>
         <% end %>
         <% unless item.quantity.nil? %>
           <p>Quantity: <%= item.quantity %></p>
         <% end %>
       </div>
       <div style="background-color: white; flex: 2;" class="glyphicon glyphicon-move" aria-hidden="true">

       </div>
       <div>
         <%= link_to "<i class='fas fa-pen'></i>".html_safe, edit_list_item_path(@list, item), class: "list-icon" %>
         <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, item_path(item), method: :delete, data: { confirm: "Are you sure?"}, class: "list-icon" %>
       </div>
     </div>
   <% end %>
 </div>
 <!-- Button trigger modal -->
<div class="center">
  <button type="button" class="signup-btn mt-3" data-toggle="modal" data-target="#exampleModal">
    Share list
  </button>
</div>

 <!-- Modal -->
 <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="exampleModalLabel">Enter email</h5>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <div class="modal-body">
         <%= form_tag new_list_email_list_path(@list), :method => "GET" do %>
           <%= text_field_tag :email, nil, :placeholder => 'Enter email address...', style: "width: 100%; height: 40px;" %>
           <%= submit_tag "Send", class: "signup-btn remove-shadow mt-3", style: "width: 100%;" %>
         <% end %>
       </div>
     </div>
   </div>
 </div>
</div>