config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "pages/profile", to: "pages#profile", as: "profile"
  resources :lists do
    member do
      get 'new_list_email'
    end
    resources :items, only: [ :index, :show, :new, :create, :edit, :update ] do
      member do
        patch 'toggle_complete'
        patch :move
      end
    end
  end
  resources :items, only: :destroy

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lists, only: [ :index, :show, :create, :destroy ] do
        resources :items, only: [ :index, :show, :update, :create, :destroy ]
      end
    end
  end
end

app/views/notifier/confirmation_instructions.html.erb
<p>Welcome <%= @email %>!</p>

<p>You can confirm your account email through the link below:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

app/views/notifier/reset_password_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

app/views/notifier/unlock_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Your account has been locked due to an excessive number of unsuccessful sign in attempts.</p>

<p>Click the link below to unlock your account:</p>

<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>