config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "pages/profile", to: "pages#profile", as: "profile"
  resources :lists do
    member do
      get 'new_list_email'
    end
    resources :items, only: [ :index, :show, :new, :create, :edit, :update ] do
      member do
        patch 'toggle_complete'
        patch :move
      end
    end
  end
  resources :items, only: :destroy

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lists, only: [ :index, :show, :create, :destroy ] do
        resources :items, only: [ :index, :show, :update, :create, :destroy ]
      end
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>© 2020 Milyst</p>
</footer>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Lists", lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to profile_path  do %>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, height: 40, :quality=>60, crop: :mfit, class: "avatar", alt: "profile image"%>
            <% else %>
              <%= image_tag "profile.png", class: "avatar"%>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>